stages:
  split:
    cmd: python src/data/data_split.py
    deps:
    - data/raw/raw.csv
    - src/data/data_split.py
    outs:
    - data/processed/X_test.csv
    - data/processed/X_train.csv
    - data/processed/y_test.csv
    - data/processed/y_train.csv
  normalize:
    cmd: python src/data/normalize.py
    deps:
    - data/processed/X_train.csv
    - src/data/normalize.py
    outs:
    - data/processed/X_test_scaled.csv
    - data/processed/X_train_scaled.csv
  grid_search:
    cmd: python src/models/grid_search.py
    deps:
    - data/processed/X_train_scaled.csv
    - data/processed/y_train.csv
    - src/models/grid_search.py
    outs:
    - models/best_params.pkl
  evaluate:
    cmd: python src/models/evaluate.py
    deps:
    - src/models/evaluate.py
    - data/processed/X_test_scaled.csv
    - data/processed/y_test.csv
    - models/gbr_model.pkl
    outs:
    - data/processed/prediction.csv
    - metrics/scores.json
